/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Doctor.java
 *
 * Created on Nov 23, 2011, 7:19:59 PM
 */

package views;

import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.awt.event.KeyListener;
import java.util.Date;
import java.util.Vector;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;
import javax.swing.event.MouseInputListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author congnguyentan
 */
public class Doctor extends javax.swing.JFrame {
    Vector columnsListDoctor;
    Vector columnsHistoryVisiting;
    Vector listOperation;

    /** Creates new form Doctor */
    public Doctor() {
        initComponents();

        columnsListDoctor = new Vector();
        columnsListDoctor.add("Order");
        columnsListDoctor.add("First Name");
        columnsListDoctor.add("Last Name");
        columnsListDoctor.add("Address");
        columnsListDoctor.add("Phone");
        columnsListDoctor.add("Birthday");
        columnsListDoctor.add("Sex");
        columnsListDoctor.add("City");
        columnsListDoctor.add("Qualification");
        columnsListDoctor.add("Professional");
        columnsListDoctor.add("doctor_id");

        listOperation = new Vector();
        listOperation.add("greater than");
        listOperation.add("greater than or equal");
        listOperation.add("equal");
        listOperation.add("not equal");
        listOperation.add("less than or equal");
        listOperation.add("less than");

        columnsHistoryVisiting = new Vector();
        columnsHistoryVisiting.add("Order");
        columnsHistoryVisiting.add("From Date");
        columnsHistoryVisiting.add("To Date");
        columnsHistoryVisiting.add("History ID");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboCountry = new javax.swing.JComboBox();
        txtValueSearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboCity = new javax.swing.JComboBox();
        cboOperation = new javax.swing.JComboBox();
        txtExperience = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cboSpecialization = new javax.swing.JComboBox();
        cmdShowAll = new javax.swing.JButton();
        cmdSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListDoctors = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHistoryVisiting = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtFirstNameEdit = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        spinnerBirthdayEdit = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        cboCountryEdit = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        txtLastNameEdit = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPhoneEdit = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cboCityEdit = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        txtEmailEdit = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtAddressEdit = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cboSexEdit = new javax.swing.JComboBox();
        txtExperienceEdit = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cboProfessionalEdit = new javax.swing.JComboBox();
        cboSpecializationEdit = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        spinnerFromDateAdd = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        spinnerToDateAdd = new javax.swing.JSpinner();
        cmdAddDoctor = new javax.swing.JButton();
        cmdEditDoctor = new javax.swing.JButton();
        cmdDeleteDoctor = new javax.swing.JButton();
        cmdAddSchedule = new javax.swing.JButton();
        cmdDeleteSchedule = new javax.swing.JButton();
        cmdViewArchivement = new javax.swing.JButton();
        cmdCloseForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Manage Doctor");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/img/top-banner.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("List Doctors");

        jLabel3.setText("Value Search:");

        jLabel4.setText("Country:");

        txtValueSearch.setToolTipText("Search on : first name, last name, address and email");

        jLabel5.setText("Experience:");

        jLabel6.setText("City:");

        txtExperience.setToolTipText("Only allow enter integer value and must greater than or equal zero");

        jLabel7.setText("Specialization:");

        cmdShowAll.setText("Show All");

        cmdSearch.setText("Search");

        tblListDoctors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblListDoctors.setFillsViewportHeight(true);
        tblListDoctors.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tblListDoctors.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblListDoctors);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("History Visiting");

        tblHistoryVisiting.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblHistoryVisiting.setFillsViewportHeight(true);
        tblHistoryVisiting.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        tblHistoryVisiting.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblHistoryVisiting);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Add/Edit Doctor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel9.setText("First Name:");

        jLabel10.setText("Birthday:");

        spinnerBirthdayEdit.setModel(new javax.swing.SpinnerDateModel());
        spinnerBirthdayEdit.setEditor(new javax.swing.JSpinner.DateEditor(spinnerBirthdayEdit, "dd/MM/yyyy"));

        jLabel11.setText("Country:");

        jLabel12.setText("Last Name:");

        jLabel13.setText("Phone:");

        txtPhoneEdit.setToolTipText("Only allow enter numeric chars and hyphen char");

        jLabel14.setText("City:");

        jLabel15.setText("Email:");

        txtEmailEdit.setToolTipText("Enter a email valid value");

        jLabel16.setText("Address:");

        jLabel17.setText("Sex:");

        jLabel18.setText("Exp:");

        cboSexEdit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        txtExperienceEdit.setToolTipText("Only allow enter integer value and must greater than or equal zero");

        jLabel21.setText("Professional:");

        jLabel22.setText("Specialization:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboCountryEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtFirstNameEdit, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spinnerBirthdayEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cboCityEdit, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPhoneEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                    .addComponent(txtLastNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAddressEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(2, 2, 2)
                                .addComponent(cboProfessionalEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtExperienceEdit)
                            .addComponent(cboSexEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cboSpecializationEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtFirstNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(txtLastNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(txtPhoneEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(spinnerBirthdayEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11)
                            .addComponent(cboCountryEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboCityEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21)
                                .addComponent(jLabel22)
                                .addComponent(cboProfessionalEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboSpecializationEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtEmailEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtAddressEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cboSexEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtExperienceEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Add Schedule Visiting", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jLabel19.setText("From Date:");

        spinnerFromDateAdd.setModel(new javax.swing.SpinnerDateModel());
        spinnerFromDateAdd.setEditor(new javax.swing.JSpinner.DateEditor(spinnerFromDateAdd, "dd/MM/yyyy"));

        jLabel20.setText("To Date:");

        spinnerToDateAdd.setModel(new javax.swing.SpinnerDateModel());
        spinnerToDateAdd.setEditor(new javax.swing.JSpinner.DateEditor(spinnerToDateAdd, "dd/MM/yyyy"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spinnerFromDateAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(spinnerToDateAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(spinnerFromDateAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(spinnerToDateAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        cmdAddDoctor.setText("Add Doctor");

        cmdEditDoctor.setText("Edit Doctor");

        cmdDeleteDoctor.setText("Delete Doctor");

        cmdAddSchedule.setText("Add Schedule");

        cmdDeleteSchedule.setText("Delete Schedule");

        cmdViewArchivement.setText("View Archivement");

        cmdCloseForm.setText("Close Form");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValueSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cboCity, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdShowAll))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 947, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(cmdAddDoctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdEditDoctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdDeleteDoctor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdViewArchivement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdAddSchedule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdDeleteSchedule)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdCloseForm)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(360, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(354, 354, 354))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtValueSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cboOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExperience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cboCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cboSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdSearch)
                            .addComponent(cmdShowAll))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdAddDoctor)
                    .addComponent(cmdEditDoctor)
                    .addComponent(cmdDeleteDoctor)
                    .addComponent(cmdViewArchivement)
                    .addComponent(cmdAddSchedule)
                    .addComponent(cmdDeleteSchedule)
                    .addComponent(cmdCloseForm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    /*function get and set data on view */

    private void _initTableListDoctor(Vector vData){
        this.tblListDoctors.setModel(new DefaultTableModel(vData, this.columnsListDoctor){
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,java.lang.String.class, java.lang.String.class,
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class,java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false,false,false,false, false, false, false,false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        this._repainTableListDoctor();
        this.tblListDoctors.setFillsViewportHeight(true);
    }

    private int[] _getRowsSelectedOnTableListDoctor(){
        int[] row = this.tblListDoctors.getSelectedRows();
        return row;
    }

    private void _removeAllValuesOnTableListDoctor(){
        Vector nullValue = null;
        this._initTableListDoctor(nullValue);
    }

    private void _repainTableListDoctor(){
        for(int j=0;j<this.tblListDoctors.getColumnCount();j++){
            int preferedWidth = 0;
            int minWidth = 0;
            int maxWidth = 0;
            //order column
            if(j==0){
                preferedWidth = minWidth = maxWidth = 50;
            }
            //first name column
            else if(j==1){
                preferedWidth = minWidth = maxWidth = 75;
            }
            //last name column
            else if(j==2){
                preferedWidth = minWidth = maxWidth = 110;
            }
            //address column
            else if(j==3){
                preferedWidth = minWidth = maxWidth = 150;
            }
            //phone column
            else if(j==4){
                preferedWidth = minWidth = maxWidth = 90;
            }
            //birthday column
            else if(j==5){
                preferedWidth = minWidth = maxWidth = 70;
            }
            //sex column
            else if(j==6){
                preferedWidth = minWidth = maxWidth = 50;
            }
            //city column
            else if(j==7){
                preferedWidth = minWidth = maxWidth = 98;
            }
            //qualification column
            else if(j==8){
                preferedWidth = minWidth = maxWidth = 109;
            }
            //professional column
            else if(j==9){
                preferedWidth = minWidth = maxWidth = 145;
            }
            //doctor id column
            else{
                preferedWidth = minWidth = maxWidth = 0;
            }
            //set width of column
            this.tblListDoctors.getColumnModel().getColumn(j).setPreferredWidth(preferedWidth);
            this.tblListDoctors.getColumnModel().getColumn(j).setMinWidth(minWidth);
            this.tblListDoctors.getColumnModel().getColumn(j).setMaxWidth(maxWidth);
            //align content of column is center
        }
    }

    public void setDataTableListDoctor(Vector vData){
        this._initTableListDoctor(vData);
    }

    public Vector getIdsDoctorSelectedOnTableListDoctor(){
        Vector result = new Vector();
        int[] rowSelected = this._getRowsSelectedOnTableListDoctor();
        for(int i=0; i<rowSelected.length; i++){
            int id = Integer.parseInt(this.tblListDoctors.getValueAt(rowSelected[i], 10).toString());

            result.add(id);
        }
        return result;
    }

    private void _initTableHistoryVisiting(Vector vData){
        this.tblHistoryVisiting.setModel(new DefaultTableModel(vData, this.columnsHistoryVisiting){
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        this._repainTableHistoryVisiting();
        this.tblHistoryVisiting.setFillsViewportHeight(true);
    }

    private int[] _getRowsSelectedOnTableHistoryVisiting(){
        int[] row = this.tblHistoryVisiting.getSelectedRows();
        return row;
    }

    private void _removeAllValuesOnTableHistoryVisiting(){
        Vector nullValue = null;
        this._initTableListDoctor(nullValue);
    }

    private void _repainTableHistoryVisiting(){
        for(int j=0;j<this.tblHistoryVisiting.getColumnCount();j++){
            int preferedWidth = 0;
            int minWidth = 0;
            int maxWidth = 0;
            //order column
            if(j==0){
                preferedWidth = minWidth = maxWidth = 50;
            }
            //from date column
            else if(j==1){
                preferedWidth = minWidth = maxWidth = 120;
            }
            //to date column
            else if(j==2){
                preferedWidth = minWidth = maxWidth = 120;
            }
            //history id column
            else{
                preferedWidth = minWidth = maxWidth = 0;
            }
            //set width of column
            this.tblHistoryVisiting.getColumnModel().getColumn(j).setPreferredWidth(preferedWidth);
            this.tblHistoryVisiting.getColumnModel().getColumn(j).setMinWidth(minWidth);
            this.tblHistoryVisiting.getColumnModel().getColumn(j).setMaxWidth(maxWidth);
            //align content of column is center
        }
    }

    public void setDataTableHistoryVisiting(Vector vData){
        this._initTableHistoryVisiting(vData);
    }

    public Vector getIdsDoctorSelectedOnHistoryVisiting(){
        Vector result = new Vector();
        int[] rowSelected = this._getRowsSelectedOnTableHistoryVisiting();
        for(int i=0; i<rowSelected.length; i++){
            int id = Integer.parseInt(this.tblHistoryVisiting.getValueAt(rowSelected[i], 3).toString());

            result.add(id);
        }
        return result;
    }

    public void setOperationExpSearch(){
        this.cboOperation.removeAllItems();
        this.cboOperation.addItem("--Operation--");
        for(int i = 0;i<this.listOperation.size();i++){
            String label = this.listOperation.get(i).toString();
            this.cboOperation.addItem(label);
        }
    }

    public String getOperationExpSearch(){
        return this.cboOperation.getSelectedItem().toString();
    }

    public void resetOperationExpSearch(){
        this.cboOperation.setSelectedItem("--Operation--");
    }

    public void setCountrySearch(Vector countries){
        this.cboCountry.removeAllItems();
        this.cboCountry.addItem("--Select Country--");
        for(int i = 0;i<countries.size();i++){
            Vector element = (Vector) countries.get(i);
            String label = element.get(1).toString();
            this.cboCountry.addItem(label);
        }
    }

    public String getCountrySearch(){
        return this.cboCountry.getSelectedItem().toString();
    }

    public void setCitySearch(Vector cities){
        this.cboCity.removeAllItems();
        this.cboCity.addItem("--Select City--");
        for(int i = 0;i<cities.size();i++){
            Vector element = (Vector) cities.get(i);
            String label = element.get(1).toString();
            this.cboCity.addItem(label);
        }
    }

    public String getCitySearch(){
        return this.cboCity.getSelectedItem().toString();
    }

    public void setSpecializationSearch(Vector specialization){
        this.cboSpecialization.removeAllItems();
        this.cboSpecialization.addItem("--Select Specialization--");
        for(int i = 0;i<specialization.size();i++){
            Vector element = (Vector) specialization.get(i);
            String label = element.get(1).toString();
            this.cboSpecialization.addItem(label);
        }
    }

    public String getSpecializationSearch(){
        return this.cboSpecialization.getSelectedItem().toString();
    }

    public void setValueSearch(String value){
        this.txtValueSearch.setText(value);
    }

    public String getValueSearch(){
        return this.txtValueSearch.getText().trim();
    }

    public void setExpValueSearch(String value){
        this.txtExperience.setText(value);
    }

    public String getExpValueSearch(){
        return this.txtExperience.getText().trim();
    }

    /*end function get and set data on view */

    /*function get and set button's status on view */

    public void setStatusAddDoctorButton(boolean status){
        this.cmdAddDoctor.setEnabled(status);
    }

    public void setStatusEditDoctorButton(boolean status){
        this.cmdEditDoctor.setEnabled(status);
    }

    public void setStatusDeleteDoctorButton(boolean status){
        this.cmdDeleteDoctor.setEnabled(status);
    }

    public void setStatusAddScheduleButton(boolean status){
        this.cmdAddSchedule.setEnabled(status);
    }

    public void setStatusDeleteScheduleButton(boolean status){
        this.cmdDeleteSchedule.setEnabled(status);
    }

    public void setStatusViewArchivementButton(boolean status){
        this.cmdViewArchivement.setEnabled(status);
    }

    public void setStatusSearchButton(boolean status){
        this.cmdDeleteSchedule.setEnabled(status);
    }

    public void setStatusShowAllButton(boolean status){
        this.cmdViewArchivement.setEnabled(status);
    }

    public void setStatusTableListDoctor(boolean status){
        this.tblListDoctors.setEnabled(status);
    }

    public void setStatusTableHistoryVisiting(boolean status){
        this.tblHistoryVisiting.setEnabled(status);
    }

    /*end function get and set button's status on view */

    /*function get and set value of form add/edit doctor on view */

    public void setFirstName(String firstName){
        this.txtFirstNameEdit.setText(firstName);
    }

    public String getFirstName(){
        return this.txtFirstNameEdit.getText().trim();
    }

    public void setLastName(String lastName){
        this.txtLastNameEdit.setText(lastName);
    }

    public String getLastName(){
        return this.txtLastNameEdit.getText().trim();
    }

    public void setEmail(String email){
        this.txtEmailEdit.setText(email);
    }

    public String getEmail(){
        return this.txtEmailEdit.getText().trim();
    }

    public void setAddress(String address){
        this.txtAddressEdit.setText(address);
    }

    public String getAddress(){
        return this.txtAddressEdit.getText().trim();
    }

    public void setPhone(String phone){
        this.txtPhoneEdit.setText(phone);
    }

    public String getPhone(){
        return this.txtPhoneEdit.getText().trim();
    }

    public void setExpEdit(String exp){
        this.txtExperienceEdit.setText(exp);
    }

    public String getExpEdit(){
        return this.txtExperienceEdit.getText().trim();
    }

    public void setCountryEditSelected(String optionSelected){
        this.cboCountryEdit.setSelectedItem(optionSelected);
    }

    public String getCountryEditSelected(){
        String optionSelected =  "";
        optionSelected = this.cboCountryEdit.getSelectedItem().toString();
        return optionSelected;
    }

    public void setCountryEdit(Vector countries){
        this.cboCountryEdit.removeAllItems();
        this.cboCountryEdit.addItem("--Select Country--");
        for(int i = 0;i<countries.size();i++){
            Vector element = (Vector) countries.get(i);
            String label = element.get(1).toString();
            this.cboCountryEdit.addItem(label);
        }
    }

    public void setCityEditSelected(String optionSelected){
        this.cboCityEdit.setSelectedItem(optionSelected);
    }

    public String getCityEditSelected(){
        String optionSelected =  "";
        optionSelected = this.cboCityEdit.getSelectedItem().toString();
        return optionSelected;
    }

    public void setCityEdit(Vector cities){
        this.cboCityEdit.removeAllItems();
        this.cboCityEdit.addItem("--Select City--");
        for(int i = 0;i<cities.size();i++){
            Vector element = (Vector) cities.get(i);
            String label = element.get(1).toString();
            this.cboCityEdit.addItem(label);
        }
    }

    public void setProfessionalEditSelected(String optionSelected){
        this.cboProfessionalEdit.setSelectedItem(optionSelected);
    }

    public String getProfessionalEditSelected(){
        String optionSelected =  "";
        optionSelected = this.cboProfessionalEdit.getSelectedItem().toString();
        return optionSelected;
    }

    public void setProfessionalEdit(Vector professionals){
        this.cboProfessionalEdit.removeAllItems();
        this.cboProfessionalEdit.addItem("--Select Professional--");
        for(int i = 0;i<professionals.size();i++){
            Vector element = (Vector) professionals.get(i);
            String label = element.get(1).toString();
            this.cboProfessionalEdit.addItem(label);
        }
    }

    public void setSpecializationEditSelected(String optionSelected){
        this.cboSpecializationEdit.setSelectedItem(optionSelected);
    }

    public String getSpecializationEditSelected(){
        String optionSelected =  "";
        optionSelected = this.cboSpecializationEdit.getSelectedItem().toString();
        return optionSelected;
    }

    public void setSpecializationEdit(Vector specializations){
        this.cboSpecializationEdit.removeAllItems();
        this.cboSpecializationEdit.addItem("--Select Specialization--");
        for(int i = 0;i<specializations.size();i++){
            Vector element = (Vector) specializations.get(i);
            String label = element.get(1).toString();
            this.cboSpecializationEdit.addItem(label);
        }
    }

    public void setSexEditSelected(String optionSelected){
        this.cboSexEdit.setSelectedItem(optionSelected);
    }

    public String getSexEditSelected(){
        String optionSelected =  "";
        optionSelected = this.cboSexEdit.getSelectedItem().toString();
        return optionSelected;
    }

    public void setBirthdayEdit(Date birthDay){
        try{
            System.out.println(birthDay.toString());
            this.spinnerBirthdayEdit.getModel().setValue(birthDay);
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    public String getBirthdayEdit(){
        String birthday =  "";
        try{
            JComponent editor = this.spinnerBirthdayEdit.getEditor();
            JFormattedTextField ftf = ((JSpinner.DefaultEditor)editor).getTextField();
            birthday = ftf.getText().trim();
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
        return birthday;
    }

    /*end function get and set value of form add/edit doctor on view */

    /*function get and set value of form add schedule on view */

    public void setFromDateAdd(Date birthDay){
        try{
            System.out.println(birthDay.toString());
            this.spinnerFromDateAdd.getModel().setValue(birthDay);
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    public String getFromDateAdd(){
        String birthday =  "";
        try{
            JComponent editor = this.spinnerFromDateAdd.getEditor();
            JFormattedTextField ftf = ((JSpinner.DefaultEditor)editor).getTextField();
            birthday = ftf.getText().trim();
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
        return birthday;
    }

    public void setToDateAdd(Date birthDay){
        try{
            System.out.println(birthDay.toString());
            this.spinnerToDateAdd.getModel().setValue(birthDay);
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    public String getToDateAdd(){
        String birthday =  "";
        try{
            JComponent editor = this.spinnerToDateAdd.getEditor();
            JFormattedTextField ftf = ((JSpinner.DefaultEditor)editor).getTextField();
            birthday = ftf.getText().trim();
        } catch(Exception e){
            System.out.println(e.getMessage());
        }
        return birthday;
    }

    /*end function get and set value of form add schedule on view */

    /*function get and set button's label on view */

    public void setLabelAddDoctorButton(String label){
        this.cmdAddDoctor.setLabel(label);
    }

    public String getLabelAddDoctorButton(){
        return this.cmdAddDoctor.getLabel();
    }

    public void setLabelEditDoctorButton(String label){
        this.cmdEditDoctor.setLabel(label);
    }

    public String getLabelEditDoctorButton(){
        return this.cmdEditDoctor.getLabel();
    }

    public void setLabelAddScheduleButton(String label){
        this.cmdAddSchedule.setLabel(label);
    }

    public String getLabelAddScheduleButton(){
        return this.cmdAddSchedule.getLabel();
    }

    public void setLabelDeleteScheduleButton(String label){
        this.cmdDeleteSchedule.setLabel(label);
    }

    public String getLabelDeleteScheduleButton(){
        return this.cmdDeleteSchedule.getLabel();
    }

    /*end function get and set button's label on view */

    /*functions set action for buttons on view*/

    /*
     * set action for button Search
     *
     * @param: ActionListener als
     */
    public void setActionOnButtonSearch(ActionListener als){
        this.cmdSearch.addActionListener(als);
    }

    /*
     * set action for button Show all
     *
     * @param: ActionListener als
     */
    public void setActionOnButtonShowAll(ActionListener als){
        this.cmdShowAll.addActionListener(als);
    }

    /*
     * set action for button add doctor
     *
     * @param: ActionListener als
     */
    public void setActionOnButtonAddDoctor(ActionListener als){
        this.cmdAddDoctor.addActionListener(als);
    }

    /*
     * set action for button edit doctor
     *
     * @param: ActionListener als
     */
    public void setActionOnButtonEditDoctor(ActionListener als){
        this.cmdEditDoctor.addActionListener(als);
    }

    /*
     * set action for button delete doctor
     *
     * @param: ActionListener als
     */
    public void setActionOnButtonDeleteDoctor(ActionListener als){
        this.cmdDeleteDoctor.addActionListener(als);
    }

    /*
     * set action for button close form
     *
     * @param: ActionListener als
     */
    public void setActionOnButtonCloseForm(ActionListener als){
        this.cmdCloseForm.addActionListener(als);
    }

    /*
     * set action for combo box country search
     *
     * @param: ItemListener als
     */
    public void setActionOnListCountrySearch(ItemListener ils){
        this.cboCountry.addItemListener(ils);
    }

    /*
     * set action for combo box country edit
     *
     * @param: ItemListener als
     */
    public void setActionOnListCountryEdit(ItemListener ils){
        this.cboCountryEdit.addItemListener(ils);
    }

    /*
     * set action for button add doctor
     *
     * @param: ActionListener als
     */
    public void setActionOnButtonAddSchedule(ActionListener als){
        this.cmdAddSchedule.addActionListener(als);
    }

    /*
     * set action for button edit doctor
     *
     * @param: ActionListener als
     */
    public void setActionOnButtonDeleteSchedule(ActionListener als){
        this.cmdDeleteSchedule.addActionListener(als);
    }

    /*end functions set action for buttons on view*/

    /*functions set action for jtables on view*/

    public void addMouseListenerOnTableListDoctor(MouseInputListener mInput){
        this.tblListDoctors.addMouseListener(mInput);
    }

    public void addKeyListenerOnTableListDoctor(KeyListener kInput){
        this.tblListDoctors.addKeyListener(kInput);
    }

    public void addMouseListenerOnTableListSchedule(MouseInputListener mInput){
        this.tblHistoryVisiting.addMouseListener(mInput);
    }

    public void addKeyListenerOnTableListSchedule(KeyListener kInput){
        this.tblHistoryVisiting.addKeyListener(kInput);
    }

    /*end functions set action for jtables on view*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboCity;
    private javax.swing.JComboBox cboCityEdit;
    private javax.swing.JComboBox cboCountry;
    private javax.swing.JComboBox cboCountryEdit;
    private javax.swing.JComboBox cboOperation;
    private javax.swing.JComboBox cboProfessionalEdit;
    private javax.swing.JComboBox cboSexEdit;
    private javax.swing.JComboBox cboSpecialization;
    private javax.swing.JComboBox cboSpecializationEdit;
    private javax.swing.JButton cmdAddDoctor;
    private javax.swing.JButton cmdAddSchedule;
    private javax.swing.JButton cmdCloseForm;
    private javax.swing.JButton cmdDeleteDoctor;
    private javax.swing.JButton cmdDeleteSchedule;
    private javax.swing.JButton cmdEditDoctor;
    private javax.swing.JButton cmdSearch;
    private javax.swing.JButton cmdShowAll;
    private javax.swing.JButton cmdViewArchivement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spinnerBirthdayEdit;
    private javax.swing.JSpinner spinnerFromDateAdd;
    private javax.swing.JSpinner spinnerToDateAdd;
    private javax.swing.JTable tblHistoryVisiting;
    private javax.swing.JTable tblListDoctors;
    private javax.swing.JTextField txtAddressEdit;
    private javax.swing.JTextField txtEmailEdit;
    private javax.swing.JTextField txtExperience;
    private javax.swing.JTextField txtExperienceEdit;
    private javax.swing.JTextField txtFirstNameEdit;
    private javax.swing.JTextField txtLastNameEdit;
    private javax.swing.JTextField txtPhoneEdit;
    private javax.swing.JTextField txtValueSearch;
    // End of variables declaration//GEN-END:variables

}
