/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProfessionalView.java
 *
 * Created on Nov 22, 2011, 5:24:46 PM
 */

package View;

import Control.DBHelper;
import Model.ProfessionalModel;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import Model.Check;

/**
 *
 * @author De
 */
public class ProfessionalView extends javax.swing.JFrame {

    /** Creates new form ProfessionalView */
    DBHelper db = new DBHelper();
    Vector vLoad;
    String nameTable = "";
    public ProfessionalView() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        initComponents();
          try {
            vLoad = ProfessionalModel.getAllProfessional();
            this.loadTableProfessional(nameTable, vLoad);

        } catch (SQLException ex) {
            System.out.println(ex);
            ex.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelProfessional = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProfessional = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldProfessionalID = new javax.swing.JTextField();
        jTextFieldProfessionalName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonResert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Professional");

        jTableProfessional.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTableProfessional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProfessionalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProfessional);

        jTextFieldProfessionalID.setText("                          identity");

        jLabel2.setText("Professional_id:");

        jLabel3.setText("Professional_name *:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldProfessionalName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldProfessionalID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProfessionalID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldProfessionalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonResert.setText("Reset");
        jButtonResert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jButtonAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonResert)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButtonAdd)
                .addComponent(jButtonDelete)
                .addComponent(jButtonUpdate)
                .addComponent(jButtonResert))
        );

        javax.swing.GroupLayout jPanelProfessionalLayout = new javax.swing.GroupLayout(jPanelProfessional);
        jPanelProfessional.setLayout(jPanelProfessionalLayout);
        jPanelProfessionalLayout.setHorizontalGroup(
            jPanelProfessionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfessionalLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanelProfessionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProfessionalLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProfessionalLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        jPanelProfessionalLayout.setVerticalGroup(
            jPanelProfessionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProfessionalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelProfessional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelProfessional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        int test = 0;
        if(!this.checkProfessional())
           return;
        //ProfessionalView objProfessional = new ProfessionalView();
        ProfessionalModel objProfessional = new ProfessionalModel();
        objProfessional.setProfessional_id(jTextFieldProfessionalID.getText());
        objProfessional.setProfessional_name(jTextFieldProfessionalName.getText());
        //objProfessional.setName(txtName.getText());
        //if(jComboBox1.getSelectedItem().toString().equals("Yes")){
         //   objUser.setRole(1);
        //} else
         //   objUser.setRole(0);
        try {
            test=ProfessionalModel.insertProfessional(objProfessional);
            if(test==1) {
                JOptionPane.showMessageDialog(this,"Add sucsessful !","Inform",JOptionPane.INFORMATION_MESSAGE);
                vLoad=ProfessionalModel.getAllProfessional();
                this.loadTableProfessional(nameTable,vLoad);
            } else {
                JOptionPane.showMessageDialog(this,"Error!","Inform",JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        int show=JOptionPane.showConfirmDialog(this,"Are You sure delete ?","Inform",JOptionPane.YES_NO_OPTION);
        if(show==JOptionPane.YES_OPTION) {
            int test=0,count=0;


            int [] rArr=jTableProfessional.getSelectedRows();
            try {
                for(int i=0;i<rArr.length;i++) {
                    test=ProfessionalModel.deleteProfessional(jTableProfessional.getValueAt(rArr[i],0).toString());
                    if(test==1)
                        count++;
                }
                if(count>0) {
                    JOptionPane.showMessageDialog(this,"Deleted "+count+" record ","successful.",JOptionPane.INFORMATION_MESSAGE);
                    vLoad=ProfessionalModel.getAllProfessional();
                    this.loadTableProfessional(nameTable,vLoad);
                } else {
                    JOptionPane.showMessageDialog(this,"Error","Inform",JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        int test=0;
        if(!this.checkProfessional())
            return;
        ProfessionalModel objProfessional=new ProfessionalModel();
        objProfessional.setProfessional_id(jTextFieldProfessionalID.getText());
        objProfessional.setProfessional_name(jTextFieldProfessionalName.getText());

       try {
            test=ProfessionalModel.updateProfessional(objProfessional);
            if(test==1) {
                JOptionPane.showMessageDialog(this,"Update sucsessful !","Inform",JOptionPane.INFORMATION_MESSAGE);
                vLoad=ProfessionalModel.getAllProfessional();
                this.loadTableProfessional(nameTable,vLoad);
            } else {
                JOptionPane.showMessageDialog(this,"Error this is !","Inform",JOptionPane.ERROR_MESSAGE);

            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonResertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResertActionPerformed
        // TODO add your handling code here:
        jTextFieldProfessionalID.setText("      identity      ");
        jTextFieldProfessionalName.setText("");
    }//GEN-LAST:event_jButtonResertActionPerformed

    private void jTableProfessionalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProfessionalMouseClicked
        // TODO add your handling code here:
        int r = jTableProfessional.getSelectedRow();
        if (r < 0) {
            return;
        }
        jTextFieldProfessionalID.setText("" + jTableProfessional.getValueAt(r, 0).toString().trim());
        jTextFieldProfessionalName.setText("" + jTableProfessional.getValueAt(r, 1));
    }//GEN-LAST:event_jTableProfessionalMouseClicked
    /**
     * Method loadTableProfessional()
     * @param nameTable
     * @param vLoad
     * @throws SQLException
     */
    private void loadTableProfessional(String nameTable, Vector vLoad) throws SQLException {
       // this.ClearAll();
       // this.disableAll();
        jPanelProfessional.setVisible(true);
        try {
            modelProfessional.setNumRows(0);
            Vector columnProfessional = new Vector();
            columnProfessional.addElement("Professional ID");
            columnProfessional.addElement("Professional Name");
            modelProfessional.setColumnIdentifiers(columnProfessional);

            ProfessionalModel objProfessional = new ProfessionalModel();
            for (int i = 0; i < this.vLoad.size(); i++) {
                objProfessional = (ProfessionalModel) this.vLoad.get(i);
                Vector rowProfessional = new Vector();
                // rowSpeciality.addElement(objSpeciality.getSpecCode());
                rowProfessional.addElement(objProfessional.getProfessional_id());
                rowProfessional.addElement(objProfessional.getProfessional_name());
                modelProfessional.addRow(rowProfessional);
            }
            jTableProfessional.setModel(modelProfessional);
        } catch (Exception ex) {
            System.out.println(ex);
            ex.printStackTrace();
        }
    }

    private boolean checkProfessional(){
        Check ck = new Check();
        if (!ck.checkSpace(jTextFieldProfessionalName.getText()) || !ck.checkName(jTextFieldProfessionalName.getText())) {
            JOptionPane.showMessageDialog(this, "Professional name invalid", "Inform", JOptionPane.ERROR_MESSAGE);
            jTextFieldProfessionalName.setText("");
            jTextFieldProfessionalName.requestFocus();
            return false;
        }
        return true;
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfessionalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonResert;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelProfessional;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProfessional;
    private javax.swing.JTextField jTextFieldProfessionalID;
    private javax.swing.JTextField jTextFieldProfessionalName;
    // End of variables declaration//GEN-END:variables
  private DefaultTableModel modelProfessional = new DefaultTableModel();
}
